# Generated by Django 3.2.5 on 2023-11-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
